### ISSUE TITLE
I have downloaded the files but how do i use them ? 

### ISSUE THREAD

**Issue by whalemilker** [AndrusGerman/DDTankCalculator#2]
I can seem to open the apps. Do i need some other applications in order to use them?

**Comment by AndrusGerman** [comment]
This is the source code, basically the bones of the application. Since it's code written in '[godot](https://docs.godotengine.org/en/stable/)', you need '[godot](https://docs.godotengine.org/en/stable/)' to compile/build it.
You can open godot (Import) and then find the folder of this 'project' and hit run (press F5 or build)
![image](https://user-images.githubusercontent.com/30560543/217330009-1b529a5d-0e3a-435a-beeb-5e2af4731ab2.png)
